import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  Backpack,
  Badge,
  Ban,
  BarChart3,
  Bell,
  BellRing,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CalendarX,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CirclePlus,
  CircleUser,
  CircleX,
  Clock,
  Code,
  Coffee,
  Construction,
  Database,
  Download,
  Droplet,
  Dumbbell,
  ExternalLink,
  Eye,
  FileText,
  Flame,
  Focus,
  Gift,
  History,
  Hourglass,
  Image,
  Info,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Link,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  MapPinOff,
  Maximize,
  Medal,
  Megaphone,
  Minus,
  Package,
  PanelsTopLeft,
  Pencil,
  Plus,
  QrCode,
  RotateCcw,
  Save,
  ScanLine,
  School,
  SearchX,
  Send,
  Settings,
  Shield,
  ShieldUser,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Star,
  Ticket,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  TriangleAlert,
  Type,
  User,
  UserCog,
  UserPlus,
  UserX,
  Users,
  Utensils,
  Vibrate,
  VideoOff,
  Wallet,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  account_balance_wallet: Wallet,
  account_circle: CircleUser,
  add: Plus,
  add_circle: CirclePlus,
  add_shopping_cart: ShoppingCart,
  admin_panel_settings: ShieldUser,
  analytics: BarChart3,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_drop_down: ChevronDown,
  arrow_forward: ArrowRight,
  backpack: Backpack,
  badge: Badge,
  bar_chart: BarChart3,
  block: Ban,
  bolt: Zap,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  campaign: Megaphone,
  category: Layers,
  center_focus_strong: Focus,
  check: Check,
  check_circle: CircleCheck,
  checkroom: Shirt,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  code: Code,
  confirmation_number: Ticket,
  construction: Construction,
  dashboard: LayoutDashboard,
  dashboard_customize: PanelsTopLeft,
  database: Database,
  delete: Trash2,
  description: FileText,
  download: Download,
  edit: Pencil,
  emoji_events: Trophy,
  emoji_objects: Lightbulb,
  error: CircleX,
  error_outline: CircleAlert,
  event: Calendar,
  event_available: CalendarCheck,
  event_busy: CalendarX,
  expand_more: ChevronDown,
  fitness_center: Dumbbell,
  fullscreen: Maximize,
  group: Users,
  groups: Users,
  history: History,
  hourglass_top: Hourglass,
  how_to_reg: UserPlus,
  image: Image,
  info: Info,
  inventory_2: Package,
  leaderboard: Trophy,
  link: Link,
  local_cafe: Coffee,
  local_fire_department: Flame,
  location_on: MapPin,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  manage_accounts: UserCog,
  mark_email_read: MailCheck,
  military_tech: Medal,
  notifications: Bell,
  open_in_new: ExternalLink,
  paid: Wallet,
  pending: Clock,
  person: User,
  person_add: UserPlus,
  person_off: UserX,
  phonelink_ring: BellRing,
  photo_camera: Camera,
  progress_activity: Loader2,
  publish: Send,
  qr_code_2: QrCode,
  qr_code_scanner: ScanLine,
  redeem: Gift,
  remove: Minus,
  replay: RotateCcw,
  restaurant: Utensils,
  restart_alt: RotateCcw,
  save: Save,
  schedule: Clock,
  school: School,
  search_off: SearchX,
  settings: Settings,
  shield: Shield,
  shield_person: ShieldUser,
  shopping_bag: ShoppingBag,
  sort: ArrowUpDown,
  sports: Trophy,
  sports_basketball: CircleDot,
  sports_score: Trophy,
  sports_soccer: Circle,
  sports_tennis: Circle,
  sports_volleyball: Circle,
  stars: Star,
  storefront: ShoppingBag,
  styler: Shirt,
  title: Type,
  trending_down: TrendingDown,
  trending_flat: Minus,
  trending_up: TrendingUp,
  tune: Settings,
  vibration: Vibrate,
  videocam_off: VideoOff,
  visibility: Eye,
  warning: TriangleAlert,
  water_drop: Droplet,
  workspace_premium: Medal,
  wrong_location: MapPinOff,
};

export function resolveLucideIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? CircleAlert;
}
